apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: vue
  name: vue
  namespace: imperfect-future
spec:
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
  replicas: 1
  selector:
    matchLabels:
      app: vue
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: vue
    spec:
      containers:
        - env:
            - name: CACHE_IGNORE
              value: js|html
            - name: CACHE_PUBLIC_EXPIRATION
              value: 3d
          image: $REGISTRY/$DOCKERHUB_NAMESPACE/$REGISTRY_PREFIX-$APP_NAME:latest
          imagePullPolicy: IfNotPresent
          name: vue
          ports:
            - containerPort: 8080
              protocol: TCP
          resources:
            limits:
              cpu: 1000m
              memory: 600Mi
            requests:
              cpu: 100m
              memory: 100Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      restartPolicy: Always
      terminationGracePeriodSeconds: 30

---
apiVersion: v1
kind: Service
metadata:
  name: vue
  namespace: imperfect-future
  labels:
    app: vue
spec:
  ports:
    - name: http-app
      protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 31008
  selector:
    app: vue
  type: NodePort
  sessionAffinity: None
